project:
  type: website
  output-dir: docs

website:
  title: "AlmeidaAlin3"
  favicon: assets/favicon.ico

  sidebar:          
    style: docked
    contents:
      - index.qmd
      - section: Research
        contents:
          - research/mech_interp.ipynb

  navbar: false     

format:
  html:
    theme: cosmo
    css: assets/styles.css
    respect-user-color-scheme: false


    toc: true              
    toc-location: right    
    toc-depth: 3

    number-sections: false

execute:
  freeze: auto


