project:
  type: website
  output-dir: docs

website:
  title: "Quarto Test"

  sidebar:          
    style: docked
    contents:
      - index.qmd
      - section: Research
        contents:
          - research/mech_interp.ipynb

  navbar: false     

format:
  html:
    theme: cosmo

    toc: true              
    toc-location: right    
    toc-depth: 3

    number-sections: false

execute:
  freeze: auto

